project_id = "fygwjpdasnhaomoqdvcu"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.meta-embedded-signup]
verify_jwt = false

[functions.send-text-message]
verify_jwt = false

[functions.send-template-message]
verify_jwt = false

[functions.upload-whatsapp-media]
verify_jwt = false
